const routers = {
    home: '/',
    login: '/login',
    register: '/register',
    forgotPwd: '/forgot-password',
    resetPwd: '/reset-password',
    introduce: '/introduce',
    financialReport: '/financial-report',
    training: '/training',
    web: '/web',
    softwareDeliveryService: '/software-delivery-service',
    providentFund: '/provident-fund',
    providentFundHome: 'home',
    deposits: 'deposits',
    uploadDeposits: 'upload-deposits',
    withdraws: 'withdraw',
    verifyWithdraw: 'verify-withdraw',
    transactions: 'transactions',
    profile: 'profile',
    investment: 'investment',
    fund: 'fund',
    interestRateTable: 'interest-rate-table',
    sendFunds: 'send-funds',
    managerFund: 'manager-fund',
    partner: 'partner',
    customcare: 'customcare',
    recruitment: '/recruitment',
    contact: '/contact',
    pageNotFound: '*',
};

export default routers;
