import Logo04 from '../../assets/images/background04.png';
import Logo05 from '../../assets/images/background05.png';
import Logo06 from '../../assets/images/background06.png';
import Logo07 from '../../assets/images/background07.png';

export const DataFundAgricutural = [
    {
        id: 'agricutural_1',
        capital: 5,
        desc: 'Khuyên dùng - Nông nghiệp',
        urlImage: Logo06,
        period: 9,
        interestRate: 75,
        type: process.env.REACT_APP_TYPE_AGRICUTURAL,
    },
    {
        id: 'agricutural_1',
        capital: 5,
        desc: 'Khuyên dùng - Nông nghiệp',
        urlImage: Logo06,
        period: 10,
        interestRate: 88,
        type: process.env.REACT_APP_TYPE_AGRICUTURAL,
    },
    {
        id: 'agricutural_1',
        capital: 5,
        desc: 'Khuyên dùng - Nông nghiệp',
        urlImage: Logo06,
        period: 11,
        interestRate: 100,
        type: process.env.REACT_APP_TYPE_AGRICUTURAL,
    },
    {
        id: 'agricutural_1',
        capital: 5,
        desc: 'Khuyên dùng - Nông nghiệp',
        urlImage: Logo06,
        period: 12,
        interestRate: 114,
        type: process.env.REACT_APP_TYPE_AGRICUTURAL,
    },
    {
        id: 'agricutural_2',
        capital: 10,
        desc: 'Khuyên dùng - Nông nghiệp',
        urlImage: Logo04,
        period: 9,
        interestRate: 151,
        type: process.env.REACT_APP_TYPE_AGRICUTURAL,
    },
    {
        id: 'agricutural_2',
        capital: 10,
        desc: 'Khuyên dùng - Nông nghiệp',
        urlImage: Logo04,
        period: 10,
        interestRate: 175,
        type: process.env.REACT_APP_TYPE_AGRICUTURAL,
    },
    {
        id: 'agricutural_2',
        capital: 10,
        desc: 'Khuyên dùng - Nông nghiệp',
        urlImage: Logo04,
        period: 11,
        interestRate: 201,
        type: process.env.REACT_APP_TYPE_AGRICUTURAL,
    },
    {
        id: 'agricutural_2',
        capital: 10,
        desc: 'Khuyên dùng - Nông nghiệp',
        urlImage: Logo04,
        period: 12,
        interestRate: 228,
        type: process.env.REACT_APP_TYPE_AGRICUTURAL,
    },
    {
        id: 'agricutural_3',
        capital: 15,
        desc: 'Khuyên dùng - Nông nghiệp',
        urlImage: Logo05,
        period: 9,
        interestRate: 226,
        type: process.env.REACT_APP_TYPE_AGRICUTURAL,
    },
    {
        id: 'agricutural_3',
        capital: 15,
        desc: 'Khuyên dùng - Nông nghiệp',
        urlImage: Logo05,
        period: 10,
        interestRate: 263,
        type: process.env.REACT_APP_TYPE_AGRICUTURAL,
    },
    {
        id: 'agricutural_3',
        capital: 15,
        desc: 'Khuyên dùng - Nông nghiệp',
        urlImage: Logo05,
        period: 11,
        interestRate: 301,
        type: process.env.REACT_APP_TYPE_AGRICUTURAL,
    },
    {
        id: 'agricutural_3',
        capital: 15,
        desc: 'Khuyên dùng - Nông nghiệp',
        urlImage: Logo05,
        period: 12,
        interestRate: 342,
        type: process.env.REACT_APP_TYPE_AGRICUTURAL,
    },
    {
        id: 'agricutural_4',
        capital: 20,
        desc: 'Lợi nhuận tốt nhất - Nông nghiệp',
        urlImage: Logo07,
        period: 9,
        interestRate: 302,
        type: process.env.REACT_APP_TYPE_AGRICUTURAL,
    },
    {
        id: 'agricutural_4',
        capital: 20,
        desc: 'Lợi nhuận tốt nhất - Nông nghiệp',
        urlImage: Logo07,
        period: 10,
        interestRate: 350,
        type: process.env.REACT_APP_TYPE_AGRICUTURAL,
    },
    {
        id: 'agricutural_4',
        capital: 20,
        desc: 'Lợi nhuận tốt nhất - Nông nghiệp',
        urlImage: Logo07,
        period: 11,
        interestRate: 402,
        type: process.env.REACT_APP_TYPE_AGRICUTURAL,
    },
    {
        id: 'agricutural_4',
        capital: 20,
        desc: 'Lợi nhuận tốt nhất - Nông nghiệp',
        urlImage: Logo07,
        period: 12,
        interestRate: 456,
        type: process.env.REACT_APP_TYPE_AGRICUTURAL,
    },
];
