import Logo01 from '../../assets/images/background01.png';
import Logo02 from '../../assets/images/background02.png';
import Logo03 from '../../assets/images/background03.png';

export const DataFundUSD = [
    {
        id: 'usd_1',
        capital: '< 25M',
        desc: 'Khuyên dùng - USD',
        urlImage: Logo01,
        period: 1,
        interestRate: 0.7,
        type: process.env.REACT_APP_TYPE_USD,
    },
    {
        id: 'usd_1',
        capital: '< 25M',
        desc: 'Khuyên dùng - USD',
        urlImage: Logo01,
        period: 3,
        interestRate: 2.42,
        type: process.env.REACT_APP_TYPE_USD,
    },
    {
        id: 'usd_1',
        capital: '< 25M',
        desc: 'Khuyên dùng - USD',
        urlImage: Logo01,
        period: 6,
        interestRate: 5.52,
        type: process.env.REACT_APP_TYPE_USD,
    },
    {
        id: 'usd_1',
        capital: '< 25M',
        desc: 'Khuyên dùng - USD',
        urlImage: Logo01,
        period: 9,
        interestRate: 9.37,
        type: process.env.REACT_APP_TYPE_USD,
    },
    {
        id: 'usd_1',
        capital: '< 25M',
        desc: 'Khuyên dùng - USD',
        urlImage: Logo01,
        period: 12,
        interestRate: 14.03,
        type: process.env.REACT_APP_TYPE_USD,
    },
    {
        id: 'usd_1',
        capital: '< 25M',
        desc: 'Khuyên dùng - USD',
        urlImage: Logo01,
        period: 18,
        interestRate: 23.95,
        type: process.env.REACT_APP_TYPE_USD,
    },
    {
        id: 'usd_2',
        capital: '> 25-200M',
        desc: 'Lợi nhuận tốt nhất - USD',
        urlImage: Logo02,
        period: 1,
        interestRate: 0.8,
        type: process.env.REACT_APP_TYPE_USD,
    },
    {
        id: 'usd_2',
        capital: '> 25-200M',
        desc: 'Lợi nhuận tốt nhất - USD',
        urlImage: Logo02,
        period: 3,
        interestRate: 2.72,
        type: process.env.REACT_APP_TYPE_USD,
    },
    {
        id: 'usd_2',
        capital: '> 25-200M',
        desc: 'Lợi nhuận tốt nhất - USD',
        urlImage: Logo02,
        period: 6,
        interestRate: 6.15,
        type: process.env.REACT_APP_TYPE_USD,
    },
    {
        id: 'usd_2',
        capital: '> 25-200M',
        desc: 'Lợi nhuận tốt nhất - USD',
        urlImage: Logo02,
        period: 9,
        interestRate: 10.35,
        type: process.env.REACT_APP_TYPE_USD,
    },
    {
        id: 'usd_2',
        capital: '> 25-200M',
        desc: 'Lợi nhuận tốt nhất - USD',
        urlImage: Logo02,
        period: 12,
        interestRate: 15.39,
        type: process.env.REACT_APP_TYPE_USD,
    },
    {
        id: 'usd_2',
        capital: '> 25-200M',
        desc: 'Lợi nhuận tốt nhất - USD',
        urlImage: Logo02,
        period: 18,
        interestRate: 26.17,
        type: process.env.REACT_APP_TYPE_USD,
    },
    {
        id: 'usd_3',
        capital: '> 200-500M',
        desc: 'Lợi nhuận tốt nhất - USD',
        urlImage: Logo03,
        period: 1,
        interestRate: 0.9,
        type: process.env.REACT_APP_TYPE_USD,
    },
    {
        id: 'usd_3',
        capital: '> 200-500M',
        desc: 'Lợi nhuận tốt nhất - USD',
        urlImage: Logo03,
        period: 3,
        interestRate: 3.03,
        type: process.env.REACT_APP_TYPE_USD,
    },
    {
        id: 'usd_3',
        capital: '> 200-500M',
        desc: 'Lợi nhuận tốt nhất - USD',
        urlImage: Logo03,
        period: 6,
        interestRate: 6.78,
        type: process.env.REACT_APP_TYPE_USD,
    },
    {
        id: 'usd_3',
        capital: '> 200-500M',
        desc: 'Lợi nhuận tốt nhất - USD',
        urlImage: Logo03,
        period: 9,
        interestRate: 11.33,
        type: process.env.REACT_APP_TYPE_USD,
    },
    {
        id: 'usd_3',
        capital: '> 200-500M',
        desc: 'Lợi nhuận tốt nhất - USD',
        urlImage: Logo03,
        period: 12,
        interestRate: 16.77,
        type: process.env.REACT_APP_TYPE_USD,
    },
    {
        id: 'usd_3',
        capital: '> 200-500M',
        desc: 'Lợi nhuận tốt nhất - USD',
        urlImage: Logo03,
        period: 18,
        interestRate: 28.43,
        type: process.env.REACT_APP_TYPE_USD,
    },
];
